language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8 ./src
  - python ./src/manage.py validate_templates
  - pip check
  - python ./src/manage.py check
  - python ./src/manage.py makemigrations --check --dry-run
  - pytest ./src/tests -s
env:
  global:
    - SECRET_KEY=abc123123rrfsss