language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8 ./src
  - python ./src/manage.py validate_templates
  - pip check
  - python ./src/manage.py check
  - python ./src/manage.py makemigrations --check --dry-run
  - pytest ./src/tests -s
env:
  global:
    - SECRET_KEY=abc123DFG
    - SERVER=dev
    - ALLOWED_HOSTS=localhost
    - MEMCACHED_HOST=a
    - RABBITMQ_DEFAULT_USER=a
    - RABBITMQ_DEFAULT_PASS=a
    - RABBITMQ_DEFAULT_HOST=a
    - EMAIL_HOST=a
    - EMAIL_HOST_USER=a
    - EMAIL_HOST_PASSWORD=a
    - EMAIL_PORT=a
    - EMAIL_USE_TLS=a
    - EMAIL_BACKEND=a
    - DEFAULT_FROM_EMAIL=a
