SOURCE_PRIVATBANK = 1
SOURCE_MONOBANK = 2
SOURCE_NBU = 3
SOURCE_BUD_VSEGDA_V_KURSE = 4
SOURCE_OSCHADBANK = 5
SOURCE_AVAL = 6

SOURCE_CHOICES = (
    (SOURCE_PRIVATBANK, 'PrivatBank'),
    (SOURCE_MONOBANK, 'MonoBank'),
    (SOURCE_NBU, 'NBU'),
    (SOURCE_BUD_VSEGDA_V_KURSE, 'vkurse.dp.ua'),
    (SOURCE_OSCHADBANK, 'Oschadbank'),
    (SOURCE_AVAL, 'Aval'),
)

CURRENCY_TYPE_USD = 1
CURRENCY_TYPE_EUR = 2
CURRENCY_TYPE_RUR = 3
CURRENCY_TYPE_CHOICES = (
    (CURRENCY_TYPE_USD, 'USD'),
    (CURRENCY_TYPE_EUR, 'EUR'),
    (CURRENCY_TYPE_RUR, 'RUR'),
)

RATE_TYPE_SALE = 1
RATE_TYPE_BUY = 2
RATE_TYPE_CHOICES = (
    (RATE_TYPE_SALE, 'Sale'),
    (RATE_TYPE_BUY, 'Buy'),
)
