# Generated by Django 2.2.13 on 2020-07-05 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'NBU'), (4, 'vkurse.dp.ua'), (5, 'Oschadbank'), (6, 'Aval')])),
                ('currency_type', models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'EUR'), (3, 'RUR')])),
                ('type_rate', models.PositiveSmallIntegerField(choices=[(1, 'Sale'), (2, 'Buy')])),
            ],
        ),
    ]
