# Generated by Django 2.2.12 on 2020-06-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type_rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sale'), (2, 'Buy')]),
        ),
    ]
