# Generated by Django 2.2.12 on 2020-05-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='type_rate',
        ),
    ]
