# Generated by Django 2.2.12 on 2020-06-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20200531_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
